# Generated by Django 5.1.5 on 2025-01-30 21:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mymodel',
            old_name='datetime',
            new_name='current_datetime',
        ),
        migrations.RenameField(
            model_name='mymodel',
            old_name='githuburl',
            new_name='github_url',
        ),
    ]
